### ISSUE TITLE
Duplicate module bundler error

### ISSUE THREAD

**Issue by drewdulz** [launchdarkly/react-native-client#2]
**Describe the bug**
Duplicate module name error in bundler.
launchdarkly-react-native-client's package.json has react-native listed as a dependency and a peerDependency.
In a react native project, react-native should already be a project dependency. When bundling the app after adding launchdarkly-react-native-client we get a duplicate module error and the bundler fails.

**Expected behavior**
The package.json for launchdarkly-react-native-client should not have react-native as a dependency

**Comment by torchhound** [comment]
Hi @drewdulz we are aware of this issue and the fix is in the next patch release. Thanks for the report!

**Comment by torchhound** [comment]
As a note you should be able to delete the offending packages or the entire `node_modules` within `node_modules/launchdarkly-react-native-client/` to fix this issue.

**Comment by jwilliamson-qb** [comment]
@torchhound can you also set the peer dependencies to use ^ instead of fixed versions?

**Comment by torchhound** [comment]
@jwilliamson-qb Absolutely!

**Comment by torchhound** [comment]
This was fixed in 1.0.0!
